server:
  id: server-1
  # Server types: lobby, game
  type: lobby

settings:
  redis-uri: redis://localhost:6379/0
  mongodb-uri: mongodb://localhost/madkaos

chat:
  format: "%vault_prefix% {username} &8» &7{message}"
  command-cooldown: 1000
  message-cooldown: 1000

blocked-commands:
  - "minecraft:me"
  - "me"

spawn:
  teleport-on-join: false
  position:
    world: ""
    x: 0
    y: 0
    z: 0
    pitch: 0
    yaw: 0

slots:
  normal: 100
  vip: 100

bossbar:
  interval: 10
  messages:
   - "1"
   - "2"
   - "3"

motd: |-
  &r &r
  &r &r
  &r &r
  &r &r
  &r &r
  &r &r
  &r &r
  &r &r
  &8&m-+-------------------------------+-
  &r &r
  &r ¡Hola! &b%player_name%
  &r Bienvenid{pron} a &5&lMADKAOS NETWORK
  &r &r
  &r &7» &6&lPATREON&r &fpatreon.com/rubius
  &r &7» &3&lTWITTER&r &ftwitter.com/madkaosoficial
  &r &7» &9&lDISCORD&r &fdiscord.gg/madkaos
  &r &r
  &8&m-+-------------------------------+-
