# General server settings.
server:
  id: server-1
  type: lobby

settings:
  redis-uri: redis://localhost:6379/0
  mongodb-uri: mongodb://localhost/madkaos

# Plugin modules.
blocked-commands:
- minecraft:me
- me

chat:
  format: '%vault_prefix%{username} &8» &7{message}'
  command-cooldown: 500
  message-cooldown: 1000

join:
  title:
    enabled: true
    duration: 4
    title: "&d¡Bienvenid{pron} %player_name%!"
    subtitle: "&bEs un gusto verte por aquí"
  sound:
    enabled: true
    sound: LEVEL_UP
  motd: 
    enabled: true
    message: |-
      &r &r
      &r &r
      &r &r
      &r &r
      &r &r
      &r &r
      &r &r
      &r &r
      &8&m«-+-----------------------------+-»
      &r &r
      &r        &f☄ &5&lMadKaos&r &d&lNetwork&r &f✯
      &r &r
      &r   &9&l✦ DISCORD&r &7discord.gg/madkaos
      &r   &6&l✦ PATREON&r &7patreon.com/rubius
      &r   &b&l✦ TWITTER&r &7twitter.com/madkaosoficial
      &r &r
      &8&m«-+-----------------------------+-»


slots:
  normal: 100
  vip: 100

spawn:
  enabled: false
  teleport-on-void: true
  teleport-on-join: true
  position:
    world: ''
    x: 0
    y: 0
    z: 0
    pitch: 0
    yaw: 0

tablist:
  enabled: true
  interval: 5
  header: |-
    &r
    &r &7&m---------&r &d&lMADKAOS NETWORK &7&m---------&r 
    &bplay.madkaos.com
    &7v&f1.9 &7➡ &7v&f1.18
    &r
  footer: |-
    &r
    &7Conectados &8» &r(&b%server_online%&r)
    &r
    &lÚnete a Patreon
    &e&nwww.patreon.com/rubius
    &r
teleport:
  delay: 3
  sound: "ENDERMAN_TELEPORT"
