server:
  id: server-1
  # Server types: lobby, game
  type: lobby

settings:
  mongodb-uri: mongodb://localhost/madkaos

motd: |-
  &r
  &r
  &r
  &r
  &r
  &r
  &r
  &r
  &8&m-+-------------------------------+-
  &r
  &r ¡Hola! &b{display_name}
  &r Bienvenid{pron} a &5&lMADKAOS NETWORK
  &r
  &r &7» &6&lPATREON&r &fpatreon.com/rubius
  &r &7» &3&lTWITTER&r &ftwitter.com/madkaosoficial
  &r &7» &9&lDISCORD&r &fdiscord.gg/madkaos
  &r
  &8&m-+------------------------------+--
