name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  fly:
    aliases: ["vuelo"]
  friends:
    aliases: ["amigos", "friend"]
  gamemode:
    aliases: ["gm"]
  message:
    aliases: ["msg"]
  reply:
    aliases: ["r"]
  tp:
    aliases: []
  tpos:
    aliases: []
  vanish:
    aliases: ["v"]