name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
depend: [Milkshake-Bukkit, PlaceholderAPI, ProtocolLib]
commands:
  alts:
    aliases: []
  ban:
    aliases: []
  chatcolor:
    aliases: ["color"]
  delhome:
    aliases: []
  delwarp:
    aliases: []
  fly:
    aliases: []
  friends:
    aliases: ["friend"]
  gamemode:
    aliases: ["gm"]
  home:
    aliases: []
  message:
    aliases: ["msg"]
  mute:
    aliases: []
  reply:
    aliases: ["r"]
  report:
    aliases: []
  server:
    aliases: []
  sethome:
    aliases: []
  setspawn:
    aliases: []
  setwarp:
    aliases: []
  spawn:
    aliases: []
  tp:
    aliases: []
  tpos:
    aliases: []
  tphere:
    aliases: []
  unban:
    aliases: []
  vanish:
    aliases: ["v"]
  warp:
    aliases: ["warps"]