name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  fly:
    aliases: ["vuelo"]
  gamemode:
    aliases: ["gm"]
  friends:
    aliases: ["amigos"]
  tp:
    aliases: []
  tpos:
    aliases: []
  vanish:
    aliases: ["v"]