name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
depend: [PlaceholderAPI, Milkshake-Bukkit]
commands:
  alts:
    aliases: []
  fly:
    aliases: []
  friends:
    aliases: ["friend"]
  gamemode:
    aliases: ["gm"]
  message:
    aliases: ["msg"]
  reply:
    aliases: ["r"]
  report:
    aliases: []
  tp:
    aliases: []
  tpos:
    aliases: []
  vanish:
    aliases: ["v"]